version: '3.7'
services:
  ubuntubleu1:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: jw1ys739
    container_name: ubuntu_bleu_1
    ports:
      - '2222:22'
  ubuntubleu2:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 24iapzqc
    container_name: ubuntu_bleu_2
    ports:
      - '2223:22'
  ubuntubleu3:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 92h6qo2o
    container_name: ubuntu_bleu_3
    ports:
      - '2224:22'
  ubuntubleu4:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: q01cxzcf
    container_name: ubuntu_bleu_4
    ports:
      - '2225:22'
  ubuntubleu5:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: xn3mcoq4
    container_name: ubuntu_bleu_5
    ports:
      - '2226:22'
  ubuntubleu6:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 9pl1q2jb
    container_name: ubuntu_bleu_6
    ports:
      - '2227:22'
  ubuntubleu7:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 4meo91fo
    container_name: ubuntu_bleu_7
    ports:
      - '2228:22'
  ubuntubleu8:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: pmldwwuy
    container_name: ubuntu_bleu_8
    ports:
      - '2229:22'
  ubunturouge1:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: qsfrq8bd
    container_name: ubuntu_rouge_1
    ports:
      - '2230:22'
  ubunturouge2:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 50t73tku
    container_name: ubuntu_rouge_2
    ports:
      - '2231:22'
  ubunturouge3:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 2hhvix9m
    container_name: ubuntu_rouge_3
    ports:
      - '2232:22'
  ubunturouge4:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: g7osss0n
    container_name: ubuntu_rouge_4
    ports:
      - '2233:22'
  ubunturouge5:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: k9w3375q
    container_name: ubuntu_rouge_5
    ports:
      - '2234:22'
  ubunturouge6:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: de72ghl1
    container_name: ubuntu_rouge_6
    ports:
      - '2235:22'
  ubunturouge7:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 3ekjdwry
    container_name: ubuntu_rouge_7
    ports:
      - '2236:22'
  ubunturouge8:
    build:
      context: ../Ubuntu
      args:
        SSH_PASS: 4y80tgqe
    container_name: ubuntu_rouge_8
    ports:
      - '2237:22'

networks:
  reseau:
    driver: bridge
