version: '3.7'

services:
  ubuntu1:
    build: ../Ubuntu
    container_name: ubuntu_ssh_1

  ubuntu2:
    build: ../Ubuntu
    container_name: ubuntu_ssh_2

  ssh-router:
    image: tecnativa/tcp-proxy
    environment:
      LISTEN: ":2222"
      TALK: "ubuntu1:22"
    ports:
      - "2222:2222"
    depends_on:
      - ubuntu1

  ssh-router2:
    image: tecnativa/tcp-proxy
    environment:
      LISTEN: ":3333"
      TALK: "ubuntu2:22"
    ports:
      - "3333:3333"
    depends_on:
      - ubuntu2
